---
# Send helper script to server to help with app creation
- name: Copy helper script to server
  win_copy:
    src: roles/sites/helpers/convert_to_app.ps1
    dest: C:\convert_to_app.ps1 

# Add sites to server
- include: create_site.yml site_name={{ item }}
  with_items: '{{ sites }}'

# Clean up the helper script
- name: Remove helper script
  win_file:
    path: C:\convert_to_app.ps1
    state: absent
