# Info for archive unzipping to support more file types
pcsx_url: http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=pscx&DownloadId=923562&FileTime=130585918034470000&Build=20959
pcsx_path: C:\pcsx.msi
